version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: "friday"
    target-branch: main
    labels: ["dependencies"]
    assignees:
      - "Seyyyy"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: "friday"
    target-branch: main
    labels: ["dependencies"]
    assignees:
      - "Seyyyy"
