name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unittests:
    name: Unit tests
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Build
        run: wasm-pack build --target web --out-dir dist/pkg --release
      - name: Run tests
        run: cargo test --verbose
